server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://localhost:5432/devsolver_db
    username: devsolver_user
    password: devsolver_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50

  web:
    resources:
      static-locations: file:uploads/ # configure static file access

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB # configure multipart limits

  security:
    user:
      name: user
      password: test@pass
